backend/controllers/AdminController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use backend\models\Product;
use backend\models\Admin;
use backend\models\OrderDetail;
use backend\models\OrderItem;
use yii\db\Query;
use yii\helpers\Url;
use yii\db\Command;
use yii\filters\AccessControl;
use frontend\models\Otp;
use yii\filters\VerbFilter;

class AdminController extends Controller {

   public $layout = "webShopping";

    public function actionIndex() { 
        return $this->render('index');
    }

    public function actionLogin() {
        $model = new Admin() ;
        if ($model->load(Yii::$app->request->post())) {
            if (Yii::$app->request->isPost) {
                $pass = hash('sha256', $model->password);
                $model->password = $pass;
                $query = new Query();
                $result = $query->select("*")
                ->from("admin")
                ->where("email = '$model->email' AND password = '$model->password' ")
                ->all();
                if (!empty($result)) {
                    //kiểm tra tài khoản đã được xác minh hay chưa
                    if ($result[0]['verify'] == 1) {
                        $_SESSION['id_admin'] = $result[0]['id_admin'];
                        $_SESSION['name_admin'] = $result[0]['user_name'];
                        return $this->redirect(['index']);
                    } else {
                        echo "<script> alert('vui long xác minh tai khoan')</script>";
                        return $this->redirect(['admin/verify', 'id_admin' => $result[0]['id_admin']]);
                    }
                } else {
                    Yii::$app->session->setFlash('error', 'sai email hoặc mật khẩu không đúng');
                }
            }
        }
        return $this->render('login', ['model' => $model]);
    }
    //đăng xuất 
    public function actionLogout() {
        session_destroy();
        return $this-> redirect(['admin/login']);
    }
    // đăng ký
    public function actionRegister() {
        $model = new Admin() ;
        if ($model->load(Yii::$app->request->post())) {
            if (Yii::$app->request->isPost) {
                $token = mt_rand(100000,999999);
                $model->token=$token;
                $pass=$model->password;
                $pass_2 = $model->password_2;
                $model->password  =hash('sha256', $pass);
                $model->password_2 = hash('sha256', $pass_2);
                $qr = new Query();
                $qr->select("*")
                ->from("admin")
                ->where("email = '$model->email' LIMIT 1 ");
                $result = $qr->all();
                if (empty($result)) {
                    if ($model->password == $model->password_2) {
                        $model->save();  
                        //echo "<script> alert('đăng ký thành công') </scritp>";
                        return $this->redirect(['verify','id_admin' => $model->id_admin]);
                    } else {
                        //echo "<script> alert('mật khẩu không khớp nhau') </scritp>";
                        Yii::$app->session->setFlash('error', 'mật khẩu không khớp nhau');
                    }
                } else {
                    Yii::$app->session->setFlash('error', 'tài khoản đã tồn tại');
                }
            }
        } 
        return $this->render('register', ['model' => $model]);
    }

    public function actionVerify($id_admin) {
        $getDomain = Yii::$app->request->getHostInfo();
        $model = Admin::findOne($id_admin);
        $url = Url::toRoute(['admin/verified', 'id_admin' => "$id_admin" , 'token' => "$model->token"]);
        $sendMail = Yii::$app->mailer->compose()
                ->setFrom("toiuoc12345@gmail.com")
                ->setTo($model->email)
                ->setSubject("email xác minh tài khoản")
                ->setTextBody("ấn vào để xác minh tài khoản :".$getDomain.$url);
                // var_dump($sendMail->send()); die();
        if ($sendMail->send()) {
            echo "<script>alert('vui long check mail')</script>";
            return $this->render('verify');
        }
    } 

    public function actionVerified() {
         //o day xac minh tai khoan nguoi dung thanh cong
         $token = $_GET['token'];
         $idAdmin = $_GET['id_admin'];
         $qr = new Query() ;
         $result = $qr->select("*")
         ->from("admin")
         ->where("token= $token and id_admin = $idAdmin ")
         ->all();
         if (!empty($result)) {
             $update = Yii::$app->db->createCommand() -> update('admin',['verify' => 1], "id_admin = $idAdmin") -> execute(); 
             echo "<script>alert('xac minh thành công') </script>";
         } else { 
             Yii::$app->session->getFlash('error' , 'xác minh thất bại');
         }
         return $this->render('verified');
    }
    //tính năng quên mật khẩu
    public function actionForgotPassword() {
        $model = new Admin();
        $tokenUser = new Otp();
        if ($model->load(Yii::$app->request->post())) {
            if (Yii::$app->request->isPost) {
                $qr = new  Query();
                $qr->select("*")
                ->from("admin")
                ->where("email = '$model->email' LIMIT 1 ");
                $data = $qr->one();
                if (!empty($data)) {
                    // var_dump($data['id_admin']);die;
                    $OTP = mt_rand(100000,999999);
                    $tokenUser->otp_code = $OTP;
                    $tokenUser->user_otp = $data['id_admin'];
                    if ($tokenUser->save()) {
                        $send_mail = Yii::$app->mailer->compose()
                        ->setFrom('toiuoc12345@gmail.com')
                        ->setTo($model->email)
                        ->setSubject('Mã xác minh')
                        ->setTextBody('Đây là mã xác minh: '.$OTP);
                       if ($send_mail->send()) {
                           echo "<script>alert('vui long check mail')</script>";
                           return $this->redirect(['verify-code', 'id_admin' => $tokenUser->user_otp]);
                       } 
                    }
                } else {
                    Yii::$app->session->setFlash('error', 'tai khoan khong ton tai');
                }
            }
        }
        return $this->render('forgotPassword', ['model' => $model]);
    }
    // gửi lại otp cho người dùng
    public function actionSendOtp() {
        Yii::$app->db->createCommand() -> delete('otp','time <= DATE_SUB(NOW(), INTERVAL 60 SECOND)')->execute();
        $adminID = $_GET['id_admin'];
        $adminAccount = Admin::findOne($adminID);
        $OTP = mt_rand(100000,999999);
        $send_mail = Yii::$app->mailer->compose()
                ->setFrom('toiuoc12345@gmail.com')
                ->setTo($adminAccount->email)
                ->setSubject('Mã xác minh')
                ->setTextBody('Đây là má xác minh: '.$OTP);
                if ($send_mail->send()) {
                    $qr = Yii::$app->db->createCommand() ->insert('otp', ['user_otp' => $adminID, 'otp_code' => $OTP])->execute();
                    return $this->redirect(['verify-code', 'id_admin' => $adminID]);
                }
    }
    //xác minh otp 
    public function actionVerifyCode() {
        $model = new Otp();
        $adminID = $_GET['id_admin'];
        if ($model->load(Yii::$app->request->post())) {
            if (Yii::$app->request->isPost) {
                $qr = new Query();
                $checkToken = $qr->select("*")
                ->from("otp")
                ->where("otp_code = $model->otp_code and time >= NOW()-INTERVAL 60 SECOND")
                ->andWhere("user_otp = $adminID ")
                ->all();
                if (!empty($checkToken)) {
                    return $this->redirect(['change-password', 'id_admin' => $adminID]);
                } else {
                    echo "<script>alert('Mã OTP không đúng hoặc không hết hạn')</script>";
                }
            }
        }
        return $this->render('verifyOtp', ['model' => $model]);
    }
    //thay đổi mật khẩu 
    public function actionChangePassword() {
        $model = Admin::findOne($_GET['id_admin']);
        if ($model->load(Yii::$app->request->post())) {
            if (Yii::$app->request->isPost) {
                $model->password = hash('sha256', $model->password);
                $model->password_2 = hash('sha256', $model->password_2); 
                if ( $model->password == $model->password_2) {
                    $model->save();
                    echo "<script>alert('mật khẩu đã được thay đổi')</script>";
                    return $this->redirect(['login']);
                } else {
                    echo "<script>alert('mật không khop nhau')</script>";
                }
            }
        }
        return $this->render('changePassword', ['model' => $model]);
    }
    // kết thúc tính năng quên mật khẩu
    //đơn hàng
    public function actionOrder() {
        if (isset($_SESSION['id_admin'])) { 
            $query = new Query();
            $result = $query->select("*")
                ->from("order_detail")
                ->innerJoin('user_web_ban_sua','user_web_ban_sua.id_user = order_detail.id_user')
                ->all();
            return $this->render('orderDetail',['data'=>$result]);
        } else {
            return $this->redirect(['admin/login']);
        }
    }
    // chi tiet san pham trong don hang
    public function actionOrderDetail() {
        if (isset($_SESSION['id_admin'])) {
            if (isset ($_GET['id_order_detail'])) {
            $id_order_detail = $_GET['id_order_detail'];
            $query = new Query();
            $result = $query->select("*")
                    ->from("order_item")
                    ->innerJoin('product',' product.id_product = order_item.id_product')
                    ->where("order_item.id_order_detail = $id_order_detail")

backend/views/admin/changePassword.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
?>
<!-- đổi mật khẩu  -->
<h2>đổi mật khẩu</h2>

<?php $form = ActiveForm::begin(); ?>

<?= $form->field($model, 'password')->input('password', ['autofocus' => true , 'id' => 'password']) ?>

<div class = "error-message"></div>
<?= $form->field($model, 'password_2')->input('password', ['autofocus' => true, 'id' => 'password_2']) ?>
    
    <div class="form-group">
        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary']) ?>
    </div>

<?php ActiveForm::end() ?>
<script>
    // làm tính năng nếu mật không giống nhau hiển thị thông báo lỗi cho người dùng
    var password = document.getElementById("password");
    var password_2 = document.getElementById("password_2");
    var message = document.querySelector(".error-message");
    password_2.addEventListener('input', function(){
        if (password.value == password_2.value) {
            message.innerText = "";
        } else {
            message.innerText = "mật không khởp nhau";
        }
    })
</script>

backend/views/admin/forgotPassword.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
?>
<h2>Vui lòng nhập email </h2>
<?php $form = ActiveForm::begin(); ?>

<?= $form->field($model, 'email')->input('text', ['autofocus' => true]) ?>

<div class="form-group">
    <?= Html::submitButton('Submit', ['class' => 'btn btn-primary']) ?>
</div>

<?php ActiveForm::end(); ?>

backend/views/admin/index.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div id="index-admin">
        <h2 class ='title'>Chào mừng đến trang admin</h2>
    </div>
</body>
</html>

backend/views/admin/login.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
?>
<?php
                if (Yii::$app->session->hasFlash('error')) {
                echo '<div class="alert alert-danger">' . Yii::$app->session->getFlash('error') . '</div>';
                } ?>
<section class="vh-100 gradient-custom">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-12 col-md-8 col-lg-6 col-xl-5">
        <div class="card bg-dark text-white" style="border-radius: 1rem;">
          <div class="card-body p-5 text-center">

            <div class="mb-md-5 mt-md-4 pb-5">

              <h2 class="fw-bold mb-2 text-uppercase">Login</h2>
              <p class="text-white-50 mb-5">Please enter your login and password!</p>

            <?php $form = ActiveForm::begin() ?>

              <div class="form-outline form-white mb-4">
                <!-- <input type="email" id="typeEmailX" class="form-control form-control-lg" /> -->
                <?= $form->field($model, 'email') -> input('text', ['class' => 'form-control form-control-lg']) ?>
                <label class="form-label" for="typeEmailX">Email</label>
              </div>

              <div class="form-outline form-white mb-4">
                <!-- <input type="password" id="typePasswordX" class="form-control form-control-lg" /> -->
                <?= $form -> field($model, 'password') -> input('password', ['class' => 'form-control form-control-lg']) ?>
                <label class="form-label" for="typePasswordX">Password</label>
              </div>

              <p class="small mb-5 pb-lg-2"><a class="text-white-50" href="<?=Url::to(['admin/forgot-password']) ?>">Forgot password?</a></p>

              <button class="btn btn-outline-light btn-lg px-5" type="submit">Login</button>
            <?php ActiveForm::end() ?>
              <div class="d-flex justify-content-center text-center mt-4 pt-1">
                <a href="#!" class="text-white"><i class="fab fa-facebook-f fa-lg"></i></a>
                <a href="#!" class="text-white"><i class="fab fa-twitter fa-lg mx-4 px-2"></i></a>
                <a href="#!" class="text-white"><i class="fab fa-google fa-lg"></i></a>
              </div>

            </div>

            <div>
              <p class="mb-0">Don't have an account? <a href="<?= Url::toRoute(['register']) ?>" class="text-white-50 fw-bold">Sign Up</a>
              </p>
            </div>

          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<style>
    .gradient-custom {
/* fallback for old browsers */
background: #6a11cb;

/* Chrome 10-25, Safari 5.1-6 */
background: -webkit-linear-gradient(to right, rgba(106, 17, 203, 1), rgba(37, 117, 252, 1));

/* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
background: linear-gradient(to right, rgba(106, 17, 203, 1), rgba(37, 117, 252, 1))
}
</style>

backend/views/admin/orderDetail.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
 ?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
<div id="table-1">
    <div>
        <!-- <a class ="add-product" href ="<?= Url::toRoute(['product/create']) ?>"> Thêm sản phẩm </a> -->
    </div>
<table class ="table">
  <tr>
    <th style = "border: 1px solid;">ID</th>
    <th style = "border: 1px solid;">Tên người đặt hàng</th>
    <th style = "border: 1px solid;">số điện thoại</th>
    <th style = "border: 1px solid;">Tổng số sản phẩm</th>
    <th style = "border: 1px solid;">Tổng tiền</th>
    <th style = "border: 1px solid;">trạng thái</th>
    <th></th>
  </tr>
  <?php foreach ($data as $value) {?>
  <tr class ="table-content">
    <td><?php echo ($value['id_order_detail']); ?></td>
    <td><?php echo ($value['user_name']); ?></td>
    <td><?php echo ($value['phone']); ?></td>
    <td><?php echo ($value['quantity']); ?></td>
    <td><?php echo ($value['total_price']); ?></td>
    <?php if ($value['status'] == 1) { ?>
        <td>đang chuyển</td>
        <?php } else { ?>
            <td>chưa chuyển</td>
            <?php }?>
    <td style = "display: flex; flex-direction: column">
        <a class ="edit" href ="<?= Url::toRoute(['admin/order-detail', 'id_order_detail' => " {$value['id_order_detail']} "]) ?>">chi tiết</a>
        <a class="delete" href ="<?= Url::toRoute(['admin/order-confirmation', 'id_order_detail' => " {$value['id_order_detail']} "]) ?>">xác nhận đơn</a>
        <a class="delete" href ="<?= Url::toRoute(['admin/delete-order', 'id_order_detail' => " {$value['id_order_detail']} "]) ?>">Xóa</a>
    </td>
  </tr>
  <?php } ?>
</table>
</div>
</body>
</html>

backend/views/admin/orderItemDetail.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
 ?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
<div id="table-1">
    <div>
        <!-- <a class ="add-product" href ="<?= Url::toRoute(['product/create']) ?>"> Thêm sản phẩm </a> -->
    </div>
<table class ="table">
  <tr>
    <th style = "border: 1px solid;">ID</th>
    <th style = "border: 1px solid;">Tên sản phẩm</th>
    <th style = "border: 1px solid;">Hình ảnh sản phẩm</th>
    <th style = "border: 1px solid;">số lượng sản phẩm</th>
    <th style = "border: 1px solid;">giá sản phẩm trên 1</th>
    <th></th>
  </tr>
  <?php foreach ($model as $value) {?>
  <tr class ="table-content">
    <td><?php echo ($value['id_product']); ?></td>
    <td><?php echo ($value['product_name']); ?></td>
    <td><img class ="image" src ="<?php echo "../imgs/".$value['product_image'] ?>" ></td>
    <td><?php echo ($value['quantity_order_item']); ?></td>
    <td><?php echo ($value['product_price']); ?></td>
    <td>
        <a class="delete" href ="<?= Url::toRoute(['admin/delete-order-item', 'id_order_item' => " {$value['id_order_item']} "]) ?>">Xóa</a>
    </td>
  </tr>
  <?php } ?>
</table>
</div>
</body>
</html>

backend/views/admin/register.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;
?>
<!-- hiển thị thông báo lỗi -->
<?php
                if (Yii::$app->session->hasFlash('error')) {
                echo '<div class="alert alert-danger">' . Yii::$app->session->getFlash('error') . '</div>';
                } ?>
<section class="vh-100" style="background-color: #eee;">
  <div class="container h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-lg-12 col-xl-11">
        <div class="card text-black" style="border-radius: 25px;">
          <div class="card-body p-md-5">
            <div class="row justify-content-center">
              <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">

                <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Sign up</p>

                <!-- <form class="mx-1 mx-md-4"> -->
                <?php $form = ActiveForm::begin(['class' => 'mx-1 mx-md-4']) ?>
                  <div class="d-flex flex-row align-items-center mb-4">
                    <i class="fas fa-user fa-lg me-3 fa-fw"></i>
                    <div class="form-outline flex-fill mb-0">
                      <!-- <input type="text" id="form3Example1c" class="form-control" /> -->
                      <?= $form->field($model, 'user_name') -> input('text', ['id' => 'user_name', 'class' => 'form-control']) ?>
                      <label class="form-label" for="form3Example1c">Your Name</label>
                    </div>
                  </div>

                  <div class="d-flex flex-row align-items-center mb-4">
                    <i class="fas fa-envelope fa-lg me-3 fa-fw"></i>
                    <div class="form-outline flex-fill mb-0">
                      <!-- <input type="email" id="form3Example3c" class="form-control" /> -->
                      <?= $form->field($model, 'email') -> input('text', ['id' => 'email', 'class' => 'form-control']) ?>
                      <label class="form-label" for="form3Example3c">Your Email</label>
                    </div>
                  </div>

                  <div class="d-flex flex-row align-items-center mb-4">
                    <i class="fas fa-lock fa-lg me-3 fa-fw"></i>
                    <div class="form-outline flex-fill mb-0">
                      <!-- <input type="password" id="form3Example4c" class="form-control" /> -->
                      <?= $form->field($model, 'password') -> input('password', ['id' => 'password', 'class' => 'form-control', 'maxLength' =>8]) ?>
                      <label class="form-label" for="form3Example4c">Password</label>
                    </div>
                  </div>

                  <div class="d-flex flex-row align-items-center mb-4">
                    <i class="fas fa-key fa-lg me-3 fa-fw"></i>
                    <div class="form-outline flex-fill mb-0">
                    <div id = "show_error" style = "color: red">  </div>
                      <!-- <input type="password" id="form3Example4cd" class="form-control" /> -->
                      <?= $form->field($model, 'password_2') -> input('password', ['id' => 'password_2', 'class' => 'form-control', 'maxLength' =>8]) ?>
                      <label class="form-label" for="form3Example4cd">Repeat your password</label>
                    </div>
                  </div>
          
                  <div class="form-check d-flex justify-content-center mb-5">
                    <input class="form-check-input me-2" type="checkbox" value="" id="form2Example3c" />
                    <label class="form-check-label" for="form2Example3">
                      I agree all statements in <a href="#!">Terms of service</a>
                    </label>
                  </div>

                  <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                    <button type="submit" class="btn btn-primary btn-lg" id = "dang_ky">Register</button>
                  </div>

                <!-- </form> -->
                <?php ActiveForm::end()?>

              </div>
              <div class="col-md-10 col-lg-6 col-xl-7 d-flex align-items-center order-1 order-lg-2">

                <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-registration/draw1.webp"
                  class="img-fluid" alt="Sample image">

              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<script>

</script>

backend/views/admin/verified.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h2> xác minh tnanh công </h2>
    <a href = "<?= Url::to(['admin/login']) ?>"> quay lại đăng nhập </a>
</body>
</html>

backend/views/admin/verify.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1 style = "text-align: center;"> vui lòng xách minh email </h1>
</body>
</html>

backend/views/admin/verifyOtp.php
<!-- xác minh OTP -->
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;
?>
<h2>Xác minh OTP</h2>
<?php $form = ActiveForm::begin(); ?>

<?= $form->field($model, 'otp_code')->input('text', ['autofocus' => true]) ?>

<div class="form-group">
    <?= Html::submitButton('Submit', ['class' => 'btn btn-primary']) ?>
</div>
<?php ActiveForm::end() ?>
<a href = "<?= Url::to(['admin/send-otp', 'id_admin' => $_GET['id_admin']])?>"> Gửi lại mã xác nhận </a>