backend/controllers/AdminController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use backend\models\Product;
use backend\models\Admin;
use backend\models\OrderDetail;
use backend\models\OrderItem;
use yii\db\Query;
use yii\helpers\Url;
use yii\db\Command;
use yii\filters\AccessControl;
use frontend\models\Otp;
use yii\filters\VerbFilter;

class AdminController extends Controller {

   public $layout = "webShopping";

    public function actionIndex() { 
        return $this->render('index');
    }

    public function actionLogin() {
        $model = new Admin() ;
        if ($model->load(Yii::$app->request->post())) {
            if (Yii::$app->request->isPost) {
                $pass = hash('sha256', $model->password);
                $model->password = $pass;
                $query = new Query();
                $result = $query->select("*")
                ->from("admin")
                ->where("email = '$model->email' AND password = '$model->password' ")
                ->all();
                if (!empty($result)) {
                    //kiểm tra tài khoản đã được xác minh hay chưa
                    if ($result[0]['verify'] == 1) {
                        $_SESSION['id_admin'] = $result[0]['id_admin'];
                        $_SESSION['name_admin'] = $result[0]['user_name'];
                        return $this->redirect(['index']);
                    } else {
                        echo "<script> alert('vui long xác minh tai khoan')</script>";
                        return $this->redirect(['admin/verify', 'id_admin' => $result[0]['id_admin']]);
                    }
                } else {
                    Yii::$app->session->setFlash('error', 'sai email hoặc mật khẩu không đúng');
                }
            }
        }
        return $this->render('login', ['model' => $model]);
    }
    //đăng xuất 
    public function actionLogout() {
        session_destroy();
        return $this-> redirect(['admin/login']);
    }
    // đăng ký
    public function actionRegister() {
        $model = new Admin() ;
        if ($model->load(Yii::$app->request->post())) {
            if (Yii::$app->request->isPost) {
                $token = mt_rand(100000,999999);
                $model->token=$token;
                $pass=$model->password;
                $pass_2 = $model->password_2;
                $model->password  =hash('sha256', $pass);
                $model->password_2 = hash('sha256', $pass_2);
                $qr = new Query();
                $qr->select("*")
                ->from("admin")
                ->where("email = '$model->email' LIMIT 1 ");
                $result = $qr->all();
                if (empty($result)) {
                    if ($model->password == $model->password_2) {
                        $model->save();  
                        //echo "<script> alert('đăng ký thành công') </scritp>";
                        return $this->redirect(['verify','id_admin' => $model->id_admin]);
                    } else {
                        //echo "<script> alert('mật khẩu không khớp nhau') </scritp>";
                        Yii::$app->session->setFlash('error', 'mật khẩu không khớp nhau');
                    }
                } else {
                    Yii::$app->session->setFlash('error', 'tài khoản đã tồn tại');
                }
            }
        } 
        return $this->render('register', ['model' => $model]);
    }

    public function actionVerify($id_admin) {
        $getDomain = Yii::$app->request->getHostInfo();
        $model = Admin::findOne($id_admin);
        $url = Url::toRoute(['admin/verified', 'id_admin' => "$id_admin" , 'token' => "$model->token"]);
        $sendMail = Yii::$app->mailer->compose()
                ->setFrom("toiuoc12345@gmail.com")
                ->setTo($model->email)
                ->setSubject("email xác minh tài khoản")
                ->setTextBody("ấn vào để xác minh tài khoản :".$getDomain.$url);
                // var_dump($sendMail->send()); die();
        if ($sendMail->send()) {
            echo "<script>alert('vui long check mail')</script>";
            return $this->render('verify');
        }
    } 

    public function actionVerified() {
         //o day xac minh tai khoan nguoi dung thanh cong
         $token = $_GET['token'];
         $idAdmin = $_GET['id_admin'];
         $qr = new Query() ;
         $result = $qr->select("*")
         ->from("admin")
         ->where("token= $token and id_admin = $idAdmin ")
         ->all();
         if (!empty($result)) {
             $update = Yii::$app->db->createCommand() -> update('admin',['verify' => 1], "id_admin = $idAdmin") -> execute(); 
             echo "<script>alert('xac minh thành công') </script>";
         } else { 
             Yii::$app->session->getFlash('error' , 'xác minh thất bại');
         }
         return $this->render('verified');
    }
    //tính năng quên mật khẩu
    public function actionForgotPassword() {
        $model = new Admin();
        $tokenUser = new Otp();
        if ($model->load(Yii::$app->request->post())) {
            if (Yii::$app->request->isPost) {
                $qr = new  Query();
                $qr->select("*")
                ->from("admin")
                ->where("email = '$model->email' LIMIT 1 ");
                $data = $qr->one();
                if (!empty($data)) {
                    // var_dump($data['id_admin']);die;
                    $OTP = mt_rand(100000,999999);
                    $tokenUser->otp_code = $OTP;
                    $tokenUser->user_otp = $data['id_admin'];
                    if ($tokenUser->save()) {
                        $send_mail = Yii::$app->mailer->compose()
                        ->setFrom('toiuoc12345@gmail.com')
                        ->setTo($model->email)
                        ->setSubject('Mã xác minh')
                        ->setTextBody('Đây là mã xác minh: '.$OTP);
                       if ($send_mail->send()) {
                           echo "<script>alert('vui long check mail')</script>";
                           return $this->redirect(['verify-code', 'id_admin' => $tokenUser->user_otp]);
                       } 
                    }
                } else {
                    Yii::$app->session->setFlash('error', 'tai khoan khong ton tai');
                }
            }
        }
        return $this->render('forgotPassword', ['model' => $model]);
    }
    // gửi lại otp cho người dùng
    public function actionSendOtp() {
        Yii::$app->db->createCommand() -> delete('otp','time <= DATE_SUB(NOW(), INTERVAL 60 SECOND)')->execute();
        $adminID = $_GET['id_admin'];
        $adminAccount = Admin::findOne($adminID);
        $OTP = mt_rand(100000,999999);
        $send_mail = Yii::$app->mailer->compose()
                ->setFrom('toiuoc12345@gmail.com')
                ->setTo($adminAccount->email)
                ->setSubject('Mã xác minh')
                ->setTextBody('Đây là má xác minh: '.$OTP);
                if ($send_mail->send()) {
                    $qr = Yii::$app->db->createCommand() ->insert('otp', ['user_otp' => $adminID, 'otp_code' => $OTP])->execute();
                    return $this->redirect(['verify-code', 'id_admin' => $adminID]);
                }
    }
    //xác minh otp 
    public function actionVerifyCode() {
        $model = new Otp();
        $adminID = $_GET['id_admin'];
        if ($model->load(Yii::$app->request->post())) {
            if (Yii::$app->request->isPost) {
                $qr = new Query();
                $checkToken = $qr->select("*")
                ->from("otp")
                ->where("otp_code = $model->otp_code and time >= NOW()-INTERVAL 60 SECOND")
                ->andWhere("user_otp = $adminID ")
                ->all();
                if (!empty($checkToken)) {
                    return $this->redirect(['change-password', 'id_admin' => $adminID]);
                } else {
                    echo "<script>alert('Mã OTP không đúng hoặc không hết hạn')</script>";
                }
            }
        }
        return $this->render('verifyOtp', ['model' => $model]);
    }
    //thay đổi mật khẩu 
    public function actionChangePassword() {
        $model = Admin::findOne($_GET['id_admin']);
        if ($model->load(Yii::$app->request->post())) {
            if (Yii::$app->request->isPost) {
                $model->password = hash('sha256', $model->password);
                $model->password_2 = hash('sha256', $model->password_2); 
                if ( $model->password == $model->password_2) {
                    $model->save();
                    echo "<script>alert('mật khẩu đã được thay đổi')</script>";
                    return $this->redirect(['login']);
                } else {
                    echo "<script>alert('mật không khop nhau')</script>";
                }
            }
        }
        return $this->render('changePassword', ['model' => $model]);
    }
    // kết thúc tính năng quên mật khẩu
    //đơn hàng
    public function actionOrder() {
        if (isset($_SESSION['id_admin'])) { 
            $query = new Query();
            $result = $query->select("*")
                ->from("order_detail")
                ->innerJoin('user_web_ban_sua','user_web_ban_sua.id_user = order_detail.id_user')
                ->all();
            return $this->render('orderDetail',['data'=>$result]);
        } else {
            return $this->redirect(['admin/login']);
        }
    }
    // chi tiet san pham trong don hang
    public function actionOrderDetail() {
        if (isset($_SESSION['id_admin'])) {
            if (isset ($_GET['id_order_detail'])) {
            $id_order_detail = $_GET['id_order_detail'];
            $query = new Query();
            $result = $query->select("*")
                    ->from("order_item")
                    ->innerJoin('product',' product.id_product = order_item.id_product')
                    ->where("order_item.id_order_detail = $id_order_detail")

backend/controllers/UserController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use backend\models\User;

class UserController extends Controller {
    public $layout = "webShopping";

    public function actionIndex() {
        if(isset($_SESSION['id_admin'])) {
        $model = User::find()->all();
        return $this->render('index',['model' => $model]);
        } else {
            return $this->redirect(['admin/login']);
        }
    }

    public function actionDelete($id_user) {
        if (isset($_SESSION['id_admin'])) {
        $model = User::findOne($id_user);
        $model->delete();
        return $this->redirect(['index']);
        } else {
            return $this->redirect(['admin/login']);
        }
    }
}
?>

backend/views/layouts/blank.php
<?php

/** @var yii\web\View $this */
/** @var string $content */

use backend\assets\AppAsset;
use yii\helpers\Html;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>" class="h-100">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body class="d-flex flex-column h-100">
<?php $this->beginBody() ?>

<main role="main">
    <div class="container">
        <?= $content ?>
    </div>
</main>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage();

backend/views/layouts/main.php
<?php

/** @var \yii\web\View $this */
/** @var string $content */

use backend\assets\AppAsset;
use common\widgets\Alert;
use yii\bootstrap5\Breadcrumbs;
use yii\bootstrap5\Html;
use yii\bootstrap5\Nav;
use yii\bootstrap5\NavBar;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>" class="h-100">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body class="d-flex flex-column h-100">
<?php $this->beginBody() ?>

<header>
    <?php
    NavBar::begin([
        'brandLabel' => Yii::$app->name,
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar navbar-expand-md navbar-dark bg-dark fixed-top',
        ],
    ]);
    $menuItems = [
        ['label' => 'login', 'url' => ['/admin/login']],
    ];
    if (Yii::$app->user->isGuest) {
        $menuItems[] = ['label' => 'Login', 'url' => ['/site/login']];
    }     
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav me-auto mb-2 mb-md-0'],
        'items' => $menuItems,
    ]);
    if (Yii::$app->user->isGuest) {
        echo Html::tag('div',Html::a('Login',['/site/login'],['class' => ['btn btn-link login text-decoration-none']]),['class' => ['d-flex']]);
    } else {
        echo Html::beginForm(['/site/logout'], 'post', ['class' => 'd-flex'])
            . Html::submitButton(
                'Logout (' . Yii::$app->user->identity->username . ')',
                ['class' => 'btn btn-link logout text-decoration-none']
            )
            . Html::endForm();
    }
    NavBar::end();
    ?>
</header>

<main role="main" class="flex-shrink-0">
    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</main>

<!-- <footer class="footer mt-auto py-3 text-muted">
    <div class="container">
        <p class="float-start">&copy; <?= Html::encode(Yii::$app->name) ?> <?= date('Y') ?></p>
        <p class="float-end"><?= Yii::powered() ?></p>
    </div>
</footer> -->

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage();

backend/views/layouts/webShopping.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
use frontend\assets\AppAsset;
use yii\bootstrap5\Breadcrumbs;
use yii\bootstrap5\Nav;
use yii\bootstrap5\NavBar;

AppAsset::register($this);
$jsFile = '../assets/password.js';

// Nhúng file JavaScript
$this->registerJsFile($jsFile);

/* @var $this yii\web\View */
/* @var $content string */
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0" />
</head>
<body>
<?php $this->beginBody() ?>
    <header>
      <div id="header-admin"> 
            <div class= "home-admin"><a href ="<?= Url::toRoute(['admin/index']) ?>"> Home </a> </div>
            <div class = 'account'>
                <?php if(isset($_SESSION['id_admin']) && isset($_SESSION['name_admin'])) { ?>
                    <div><a href ="<?= Url::toRoute(['admin/logout']) ?>">Logout : <?php echo "xin chào:".$_SESSION['name_admin'] ?> </a> </div>
                <?php } else { ?>
                    <div class = "login-admin"><a href ="<?= Url::toRoute(['admin/login']) ?>">Login </a></div> 
                    <div> &#x7C; </div>
                    <div class = "sigip-admin"><a href ="<?= Url::toRoute(['admin/register']) ?>"> sigup </a></div>
                    <?php } ?>
            </div>
      </div>
    </header>
    <main role="main" class="flex-shrink-0">
    <div class="container" >
        <div style = "display: block; padding: 10px; border: 1px solid black;border-radius: 20px;
    background-color: #b834bc ;min-width: 910px;">
            <div id= "menu">
                <div class ='item'>
                    <a href ="<?= Url::toRoute(['product/index']) ?>">Quản lý sản phẩm</a>
                </div>
                <div class ='item'>
                    <a href ="<?= Url::toRoute(['product/size']) ?>">Quản lý kích thước sản phẩm</a>
                </div>
                <div class ='item'>
                    <a href ="<?= Url::toRoute(['user/index']) ?>">Quản lý tài khoản User</a>
                </div>
                <div class ='item'>
                    <a href ="<?= Url::toRoute(['product/categorys']) ?>">Quản lý danh mục sản phẩm</a>
                </div>
                <div class ='item'>
                    <a href ="<?= Url::toRoute(['admin/order']) ?>">Quản lý danh sách đơn hàng</a>
                </div>
                <div class ='item'>
                    <a href ="<?= Url::toRoute(['reviews/index']) ?>">reviews sản phẩm</a>
                </div>
            </div>
        </div>
        <?= $content ?>
    </div>
</main>
<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>