frontend/controllers/HomeController.php
<?php
namespace frontend\controllers;

use yii\web\Controller;
use backend\models\Product;
use yii\db\Query;
use backend\models\ProductCategorys;
use backend\models\OrderDetail;
use backend\models\OrderItem;
use backend\models\ProductReviews;
use yii\helpers\Url;
use Yii;

class HomeController extends Controller {
    // public $layout = "layoutIndex";
    public $replace = ['a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'd', 'e', 'e', 'e', 'e', 'e', 'e', 'i', 'i', 'i', 'i', 'i', 'o', 'o', 'o', 'o', 'o', 'o', 'o', 'o', 'o', 'o', 'o', 'o', 'o', 'o', 'o', 'o', 'u', 'u', 'u', 'u', 'u', 'u', 'u', 'u', 'u', '-',];
    public $search = ['ã', 'à', 'á', 'ả', 'ạ', 'â', 'ẩ', 'ấ', 'ẫ', 'ầ', 'ậ', 'ẵ', 'ă', 'ẳ', 'ằ', 'ặ', 'ắ', 'đ', 'ễ', 'ê', 'ể', 'ế', 'ề', 'ệ', 'ỉ', 'ì', 'ĩ', 'í', 'ị', 'õ', 'ò', 'ó', 'ọ', 'ỏ', 'ô', 'ỗ', 'ồ', 'ố', 'ộ', 'ổ', 'ỡ', 'ơ', 'ớ', 'ờ', 'ở', 'ù', 'ú', 'ủ', 'ụ', 'ư', 'ứ', 'ừ', 'ử', 'ự', ' ',];
    public $layout = 'header';
    public function actions()
    {
        return [
            'error' => [
                'class' => \yii\web\ErrorAction::class,
            ],
            'captcha' => [
                'class' => \yii\captcha\CaptchaAction::class,
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionIndex() {
        //$model = Product::find()->all();
        $query = new Query();
        $qr = new Query();
        $getDomain = Yii::$app->request->getHostInfo();
        $result = $query->select('*')
        ->from('product')
        ->innerJoin('product_categorys','product.id_product_categorys = product_categorys.id_product_categorys LIMIT 10')
        ->all();
        // $product = $qr->select('*')
        // ->from('product')
        // ->all();
        // foreach ($product as &$item) {
        //     $item['url'] = $getDomain.Url::to(['home/product-info', 'id_product' => $item['id_product']]);
        //     //var_dump($item);
        // }
        // $jsonProduct = json_encode($product);
        // $this->view->params['paras'] = $jsonProduct;
        return $this->render('index',['model' => $result]);
    }
    public function getCategories() {
        $query = new Query();
        $result = $query->select('*')
        ->from('product_categorys')
        ->all();
        return $result;
    }

    public function actionProductInfo($product_name,$id_product) {
        $model = Product::findOne($id_product);
        $qr = new Query();
        $qr->select("*")
        ->from("product_size")
        ->innerJoin('product','product.id_product = product_size.id_product')
        ->innerJoin('size','size.id_size = product_size.id_size')
        ->where("product.id_product = $id_product");
        $result = $qr->all();
        $query = new Query();
        $query->select('*')
        ->from("product_reviews")
        ->innerJoin('product','product.id_product = product_reviews.id_product')
        ->innerJoin('user_web_ban_sua','user_web_ban_sua.id_user = product_reviews.id_user')
        ->where(['product.id_product' => $id_product])
        ->limit(10);
        $dataReviews= $query->all();
        $getTotalUserReview = new Query();
        $getTotalUserReview->select('count(*)')
        ->from("product_reviews")
        ->innerJoin('product','product.id_product = product_reviews.id_product')
        ->innerJoin('user_web_ban_sua','user_web_ban_sua.id_user = product_reviews.id_user')
        ->where(['product.id_product' => $id_product]);
        $totalUserReview = $getTotalUserReview->all();
        // tạo thêm query load more comment 
        $modelReviews= ProductReviews::find()->where(['id_product' => $id_product])->all();
        $qrLoadMore = new Query();
        if (isset($_POST['page'])) {
            //  thưc hiện query load more comment
        }
        // 
        return $this->render('productInfo',['model' => $model,'result' => $result,'dataReviews' => $dataReviews, 'totalUserReview' => $totalUserReview[0]['count(*)'], 'modelReviews' => $modelReviews, ]);
    }

    // giỏ hàng
    public function actionAddToCart() {
        $query = new Query();
        if (Yii::$app->request->isPost) {
            if(!empty( $_POST['quantity'])) {
                $result = $query->select('*')
                ->from('product')
                ->where("id_product = $_GET[id_product]")
                ->all();
                $itemCart=[ $result[0]['id_product']=>[
                    'id_product' => $result[0]['id_product'],
                    'product_name' => $result[0]['product_name'],
                    'product_price' => $result[0]['product_price'],
                    'quantity' => (int)$_POST['quantity'],
                    'image' => $result[0]['product_image'],
                ], 
                ];
                if (!empty($_SESSION['item_cart'])) {
                    //foreach ($_SESSION['item_cart'] as $newArray) 
                    if(in_array($result[0]['id_product'],array_keys($_SESSION['item_cart'])) ) {
                        foreach($_SESSION['item_cart'] as $k => $v) {
                            if($k == $result[0]['id_product']) {
                                if(empty($_SESSION['item_cart'][$k]['quantity'])) {
                                    $_SESSION['item_cart'][$k]['quantity'] = (int)$_POST['quantity'];
                                }
                                $_SESSION['item_cart'][$k]['quantity'] += (int)$_POST['quantity'];
                            }
                        }
                    } else {
                        $_SESSION['item_cart'] = $_SESSION['item_cart']+ $itemCart;
                    }
                } else {
                    $_SESSION['item_cart'] =  $itemCart;
                    //var_dump($_SESSION['item_cart']);
                };
            }
        }else {
                $_POST['quantity'] = 1;
                $result = $query->select('*')
                ->from('product')
                ->where("id_product = $_GET[id_product]")
                ->all();
                $itemCart=[ $result[0]['id_product']=>[
                    'id_product' => $result[0]['id_product'],
                    'product_name' => $result[0]['product_name'],
                    'product_price' => $result[0]['product_price'],
                    'quantity' => (int)$_POST['quantity'],
                    'image' => $result[0]['product_image'],
                ], 
                ];
                if (!empty($_SESSION['item_cart'])) {
                    //foreach ($_SESSION['item_cart'] as $newArray) 
                    if(in_array($result[0]['id_product'],array_keys($_SESSION['item_cart'])) ) {
                        foreach($_SESSION['item_cart'] as $k => $v) {
                            if($k == $result[0]['id_product']) {
                                if(empty($_SESSION['item_cart'][$k]['quantity'])) {
                                    $_SESSION['item_cart'][$k]['quantity'] = (int)$_POST['quantity'];
                                }
                                $_SESSION['item_cart'][$k]['quantity'] += (int)$_POST['quantity'];
                            }
                        }
                    } else {
                        $_SESSION['item_cart'] = $_SESSION['item_cart']+ $itemCart;
                    }
                } else {
                    $_SESSION['item_cart'] =  $itemCart;
                };
        }
        return $this->redirect(['cart']);
    }
    public function actionDecreaseCart() {
        if(!empty($_SESSION['item_cart'])) {
            foreach($_SESSION['item_cart'] as $k => $v) {
                if((int)$_GET['id_product'] == $_SESSION['item_cart'][$k]['id_product'] ) {
                    if ($_SESSION['item_cart'][$k]['quantity'] == 1) {
                        unset($_SESSION['item_cart'][$k]);
                    } else {
                    $_SESSION['item_cart'][$k]['quantity'] -= 1;
                    }
                } 
            }
            return $this->redirect(['cart']); 
        }
    }
    public function actionUpdateCart() {
        header('Content-Type: application/json');
        yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
       if (!empty($_SESSION['item_cart'])) {
            foreach($_SESSION['item_cart'] as $k => $v) {
                if((int)$_POST['id_product'] == $_SESSION['item_cart'][$k]['id_product'] ) {
                    $_SESSION['item_cart'][$k]['quantity'] = (int)$_POST['quantity'];
                }
            }
            //var_dump($_SESSION['item_cart']);
            //return $this->redirect(['cart']);
            $dataJson = json_encode($_SESSION['item_cart']);
            echo $dataJson;
            die(); 
            return $this->render('cart');
        }
        // $quantity = Yii::$app->request->post('quantity');
        // var_dump($quantity);
        // echo"ko";
    }
    public function actionRemoveCart() {
        if(!empty($_SESSION['item_cart'])) {
            //unset($_SESSION['item_cart'][$_GET['id_product']]);
            foreach($_SESSION['item_cart'] as $k => $v) {
                if((int)$_GET['id_product'] == $_SESSION['item_cart'][$k]['id_product'] ) {
                    unset($_SESSION['item_cart'][$k]);
                    if(empty($_SESSION["cart_item"]))
				    unset($_SESSION["cart_item"]);
                } 
            }
            return $this->redirect(['cart']); 
        }
    }
    public function actionCart() {
        //kiểm tra người dùng có tòn tại đơn hàng đã đặt nào không
        if (isset($_SESSION['id_user'])) {
            $idUser = $_SESSION['id_user'];
            $query = new Query();
            $result = $query->select('*')
            ->from('order_detail')
            ->innerJoin('user_web_ban_sua', 'user_web_ban_sua.id_user = order_detail.id_user')
            ->where("user_web_ban_sua.id_user = $idUser and order_detail.status = 0")
            ->all();

frontend/views/home/cart.php
<?php
use yii\widgets\ActiveForm;
use yii\helpers\Url;
use yii\helpers\Html;
$url1 = Url::to('@web/uploads/images/pizza-hub.jpg');
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div class="container">
        <!-- thông tin đơn hàng của người dùng nếu có -->
        <div class="title"><h2>Đơn đã đặt</h2></div>
        <?php if (isset($_SESSION['user_order']) ) { ?>
            <table style = "border: 1px solid">
                <tr style = " border: 1px solid">
                    <th style = "padding: 10px">Mã đơn</th>
                    <th style = "padding: 10px">Tên người đặt</th>
                    <th style = "padding: 10px">Số lượng</th>
                    <th style = "padding: 10px">Tổng tiền</th>
                </tr>
                <?php foreach ($userOrder as $v) { ?>
                <tr style = " border: 1px solid" >
                    <td style = "padding: 10px"><?php echo $v['id_order_detail'] ?></td>
                    <td style = "padding: 10px"><?php echo $v['user_name'] ?></td>
                    <td style = "padding: 10px"><?php echo $v['quantity'] ?></td>
                    <td style = "padding: 10px"><?php echo $v['total_price']  ?></td>
                </tr>
                <?php } ?>
            </table>
            <?php } else { ?>
                   <?php if (isset($_SESSION['id_user'])) {?>
                    <a> Hiện tại chưa có đơn hàng nào đã được đặt </a>
                   <?php } else {?>
                    <a> </a>
                    <?php } ?>
                <?php } ?>
        <!--  -->
        <div id="cart">
            <div class="title"><h2>Giỏ hàng</h2></div>
            <div class="products-cart">
            <?php $form = ActiveForm::begin(['action' => Url::toRoute(['home/oder']) , 'method' => 'post' ]) ?>
            <table class ="table">
                <tr class ="table-title">
                    <th>Tên sản phẩm</th>
                    <th>Hình ảnh</th>
                    <th>số lượng</th>
                    <th>giá sản phẩm</th>
                    <th colspan ="2"></th>
                </tr>
                <?php if (isset($_SESSION['item_cart'])) {?>
                <?php foreach($_SESSION['item_cart'] as $key => $value){ ?>
                <tr class = 'table-content'>
                    <td style = "border:none"><?php echo $value['product_name'] ?></td>
                    <td style = "border:none"> <img  src ='<?php echo('../images/'.$value['image']) ?>' style = "width:20%; height: auto"/></td>
                    <td style = "display: flex; border:none">
                        <div class = "btn-decrease-quantity" onclick ="decreaseValue(this)"><a class="decrease-cart" style ="text-decoration: none" href="<?= Url::to([ 'home/decrease-cart','id_product'=> $value['id_product'] ])?>">-</a></div>
                        <input id ='number'name ="quantity" class ="so-luong" type ='number'  value ='<?php echo $value['quantity'] ?>' min='1' max ='100' style ="text-align: center; font-size: 20px; border-radius: 10px;" >
                        <div class = "btn-increase-quantity" onclick = "increaseValue(this)"><a class="increase-cart" style ="text-decoration: none" href="<?= Url::to([ 'home/add-to-cart','id_product'=> $value['id_product'] ])?>">+</a></div>
                    </td>
                    <td style = "border:none" class = "gia-san-pham"><?php echo $value['product_price']*$value['quantity'] ?></td>
                    <td style = "border:none"><a href = "<?= Url::toRoute(['home/remove-cart', 'id_product' => $value['id_product']]) ?>" class ='btn btn-primary'  >xóa </a></td>
                </tr>
                <?php } ?>
                <tr>
                    <td>Tổng tiền: </td>
                    <td> </td>
                    <td> </td>
                    <td class ="total-quantity"></td>
                    <td class ="total">VND</td>
                </tr>
                <?php } ?>
            </table>
            <?php if (isset($_SESSION['item_cart']) && !empty( $_SESSION['item_cart'])) { ?>
                <?php if (isset($_SESSION['id_user']) ) {  ?>
                <button type="submit" class ='btn btn-primary' >Đặt mua</button>
                <?php } else { ?>
                <a href = "<?= Url::toRoute(['login/index']) ?>" class ='btn btn-primary' onclick= " alert('Vui lòng đăng nhập')">Đặt mua</a>
                <?php } ?>
            <?php } else { ?>
                <a href ="<?= Url::to(['home/index']) ?>" class ='btn btn-primary'> tiếp tục mua sắm</a>
            <?php }?>
            <?php ActiveForm::end() ?>
            </div>
        </div>
    </div>
</body>
</html>
<script>
    var total = 0;
    var quantityTotal = 0
    var productPrice= document.querySelectorAll('.gia-san-pham');
    var productQuantity= document.querySelectorAll('.so-luong');
    var showTotal = document.querySelector('.total');
    var showTotalQuantity = document.querySelector('.total-quantity');
    for (let i = 0; i < productPrice.length; i++) {
        total += parseInt(productPrice[i].innerHTML);
    }
    for (let i = 0; i < productQuantity.length; i++) {
        quantityTotal += parseInt(productQuantity[i].value);
    }
    showTotal.innerHTML= total;
    showTotalQuantity.innerHTML= quantityTotal;
</script>
<script>
 function decreaseValue(element) {
    var input = element.nextElementSibling;
    var value = parseInt(input.value, 10);
    if (value > 1) {
      input.value = value - 1;
    }
  }

  function increaseValue(element) {
    var input = element.previousElementSibling;
    var value = parseInt(input.value, 10);
    input.value = value + 1;
  }
</script>
<script>
     function total () {
        var total = 0;
    var quantityTotal = 0
    var productPrice= document.querySelectorAll('.gia-san-pham');
    var productQuantity= document.querySelectorAll('.so-luong');
    var showTotal = document.querySelector('.total');
    var showTotalQuantity = document.querySelector('.total-quantity');
    for (let i = 0; i < productPrice.length; i++) {
        total += parseInt(productPrice[i].innerHTML);
    }
    for (let i = 0; i < productQuantity.length; i++) {
        quantityTotal += parseInt(productQuantity[i].value);
    }
    showTotal.innerHTML= total;
    showTotalQuantity.innerHTML= quantityTotal;
    }
</script>

frontend/views/home/index.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
// $getUrl  =Yii::$app->request;
// $getDomain = $getUrl->getHostInfo();
// $url =Url::to(['home/index']);
//test url
// $replace = ['a','a','a','a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'd', 'e',
// 'e', 'e', 'e', 'e', 'e', 'i', 'i', 'i', 'i', 'i', 'o', 'o', 'o','o', 'o', 'o','o' ,'o' ,'o' ,'o' ,'o' ,'o' ,'o','o','o','o',
// 'u' , 'u', 'u', 'u', 'u', 'u', 'u', 'u', 'u','-'];
// $search = ['ã','à' , 'á' , 'ả' , 'ạ' ,'â', 'ẩ' , 'ấ','ẫ',
// 'ầ', 'ậ', 'ẵ','ă', 'ẳ', 'ằ' ,'ặ', 'ắ' , 'đ', 'ễ','ê', 'ể' ,'ế', 'ề' , 'ệ', 'ỉ', 'ì','ĩ',
// 'í', 'ị','õ', 'ò', 'ó', 'ọ', 'ỏ', 'ô', 'ỗ','ồ', 'ố', 'ộ', 'ổ', 'ỡ','ơ', 'ớ', 'ờ', 'ở', 'ù', 'ú','ủ', 'ụ',
// 'ư', 'ứ', 'ừ', 'ử', 'ự',' ', 
// ];
$replace = ['a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'd', 'e', 'e', 'e', 'e', 'e', 'e', 'i', 'i', 'i', 'i', 'i', 'o', 'o', 'o', 'o', 'o', 'o', 'o', 'o', 'o', 'o', 'o', 'o', 'o', 'o', 'o', 'o', 'u', 'u', 'u', 'u', 'u', 'u', 'u', 'u', 'u', '-',];
$search = ['ã', 'à', 'á', 'ả', 'ạ', 'â', 'ẩ', 'ấ', 'ẫ', 'ầ', 'ậ', 'ẵ', 'ă', 'ẳ', 'ằ', 'ặ', 'ắ', 'đ', 'ễ', 'ê', 'ể', 'ế', 'ề', 'ệ', 'ỉ', 'ì', 'ĩ', 'í', 'ị', 'õ', 'ò', 'ó', 'ọ', 'ỏ', 'ô', 'ỗ', 'ồ', 'ố', 'ộ', 'ổ', 'ỡ', 'ơ', 'ớ', 'ờ', 'ở', 'ù', 'ú', 'ủ', 'ụ', 'ư', 'ứ', 'ừ', 'ử', 'ự', ' ',];
?>
<!-- <div id="slider2"> -->
<?= $this->render('../shopping/slider.php'); ?>

</div>
<?= $this->render('../shopping/sidebar.php') ?>
<div>
<ul id="product-content-list">
    <?php foreach($model as $row) { 
        $str = str_replace($search, $replace, mb_strtolower($row['product_name']));
        ?>
    <li class="item">
        <div class="product-img">
            <a href="<?= Url::toRoute(['product-info', 'product_name' => $str, 'id_product' => $row['id_product'] ]) ?>" style ="text-decoration: none; color: black;">
                <img src="<?= Url::to(['/images/'.$row['product_image']], true) ?>" alt="">
            </a>
        </div>
        <div class="product-info">
            <h3 class="product-name">
                <a href ="<?= Url::toRoute(['product-info', 'product_name' => $str, 'id_product' => $row['id_product'] ]) ?>" style ="text-decoration: none; color: black;"><?php echo $row['product_name'] ?></a>
            </h3>
            <a class ="product-category">loại sản phẩm: 
                <a href ="<?= Url::to(['home/filter-sort-pagination', 'filter' => $row['categorys_name'] ]) ?>" style ="display: inline-block;text-decoration: none;"><?php echo $row['categorys_name'] ?></a>
            </a>
            <h3>
                <a class ="product-price"><?php echo number_format($row['product_price'], 0, ',', '.'); ?> VNĐ</a>
            </h3>
            <div>
                <i>Còn Hàng</i>
                <a href ="<?= Url::to(['home/add-to-cart', 'id_product' => $row['id_product']]) ?>" style = 'color: red' class ='btn-add-cart'>
                    <span style ="float:right;" class="material-symbols-outlined">
                    shopping_bag
                    </span>
                </a>
            </div>
        </div>
    </li>
    <?php }  ?>
</ul>
</div>
<?php $url = Url::to(['home/test']) ;
?>
<!-- <button onclick="functionTest()">test</button> -->

frontend/views/home/notificationEndpage.php
<h1> đây là lỗi</h1>

frontend/views/home/orderSuccess.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div style ="margin-top:46px">
        <h1> đặt hàng thành công </h1>
        <a href="<?= Url::to(['home/index']) ?>" class="btn btn-primary"> TIẾP TỤC MUA SẮM</a>
    </div>
</body>
</html>

frontend/views/home/pagination.php
<?php
use yii\helpers\Url;
$page = ceil($total/15);
 ?>
<!DOCTYPE html>
<html>
<head>
<style>
.pagination {
  display: inline-block;
}

.pagination a {
  color: black;
  float: left;
  padding: 8px 16px;
  text-decoration: none;
  transition: background-color .3s;
  border: 1px solid #ddd;
  margin: 0 4px;
}

.pagination a.active {
  background-color: #4CAF50;
  color: white;
  border: 1px solid #4CAF50;
}

.pagination a:hover:not(.active) {background-color: #ddd;}
</style>
</head>
<body>

<div class="pagination">
  <?php if (isset($_GET['page']) ) {
    if($_GET['page']<3) {
    ?>
    <?php } else { ?>
        <a href="<?=Url::to(['home/filter-sort-pagination', 'page' => $_GET['page']-1]) ?>">&laquo;</a>
        <?php }?>
    <?php }?>
    <a class="page" style ="background-color:red" href="<?= Url::to(['home/show-all']) ?>">1</a>
  <!--  -->
  <?php for($i=2;$i<=$page;$i++) { 
    if(isset($_GET['page'])) {
        if(isset($_GET['filter'])) {
            if(isset($_GET['sort'])) {
    ?>
    <!-- thuc hien page and sort with filter -->
    <?php if($i >= ($_GET['page']-2) && $i <= ($_GET['page']+2)) { ?>
        <a class="page" href="<?= Url::to(['home/filter-sort-pagination', 'filter' => $_GET['filter'], 'page' => $i, 'sort' => $_GET['sort']]) ?>"><?php echo $i ?></a>
        <?php } ?>
        <?php } else { ?>
            <!-- thuc hien page and filter -->
                <?php if($i >= ($_GET['page']-2) && $i <= ($_GET['page']+2)) { ?>
                <a class="page" href="<?= Url::to(['home/filter-sort-pagination', 'filter' => $_GET['filter'], 'page' => $i ]) ?>"><?php echo $i ?></a>
                <?php } ?>
            <?php }?>
        <!-- o day kiem tra dk co filter hay khong -->
        <?php } elseif (isset($_GET['sort'])) {?>
            <!-- o kiem tra dk co sort khong -->
                <?php if($i >= ($_GET['page']-2) && $i <= ($_GET['page']+2)) { ?>
                <a class="page" href="<?= Url::to(['home/filter-sort-pagination', 'page' => $i,'sort' => $_GET['sort'] ]) ?>"><?php echo $i ?></a>
                <?php } ?>
            <!-- thuc hien page and sort -->
            <?php } else { ?>
                <!-- thuc hien page -->
                    <?php if($i >= ($_GET['page']-2) && $i <= ($_GET['page']+2)) { ?>
                    <a class="page" href="<?= Url::to(['home/filter-sort-pagination', 'page' => $i, ]) ?>"><?php echo $i ?></a>
                    <?php } ?>
                <?php } ?>
        <!-- day trong dk kiem tra xem co $_GET[page] hay khong -->
    <?php } else {?>
    <!-- neu khong co page se thuc hien tao gia tri co page -->
    <?php if($i >= 2 && $i <= 6) { ?>
      <?php if(isset($_GET['filter'])) {?>
        <!-- kiểm tra co filter hay khong -->
        <?php if (isset($_GET['sort'])) {?>
            <!-- kiem tra co sort hay khong -->
            <a class="page" href="<?= Url::to(['home/filter-sort-pagination', 'filter' => $_GET['filter'], 'page' => $i, 'sort' => $_GET['sort']]) ?>"><?php echo $i ?></a>
            <?php } else {?>
                <!-- thuc hien page and filter -->
                <a class="page" href="<?= Url::to(['home/filter-sort-pagination', 'filter' => $_GET['filter'], 'page' => $i ]) ?>"><?php echo $i ?></a>
                <?php } ?>
        <?php } else { ?>
            <?php if (isset($_GET['sort'])) {?>
                <a class="page" href="<?= Url::to(['home/show-all', 'page' => $i ,'sort' => $_GET['sort']]) ?>"><?php echo $i ?></a>
                <?php } else {?>
                    <a class="page" href="<?= Url::to(['home/show-all', 'page' => $i ]) ?>"><?php echo $i ?></a>
                    <?php } ?>
            <?php } ?>
        <?php }?>
    <?php } ?>
  <!-- <a href="#"><?php echo $i ?></a> -->
  <?php }?>
  <?php if(isset($_GET['page'])) {
    if($_GET['page'] == $page or $_GET['page'] > $page) {
    ?>
    <?php } else {?>
        <!-- thuc hien tang so trang bang $_get[page]+1 -->
        <a href="<?=Url::to(['home/show-all', 'page' => $_GET['page']+1]) ?>">&raquo;</a>
        <?php } ?>
    <?php } else { ?>
        <!-- thuc hien tang so trong khi khon ton tai $get[page] -->
        <?php if(isset($_GET['filter'])) {?>
            <?php if (isset($_GET['sort'])) {?>
                <a href="<?=Url::to(['home/filter-sort-pagination', 'filter' => $_GET['filter'], 'page' => 2, 'sort' => $_GET['sort']]) ?>">&raquo;</a>
                <?php } else { ?>
                    <a href="<?=Url::to(['home/filter-sort-pagination', 'filter' => $_GET['filter'], 'page' => 2]) ?>">&raquo;</a>
                    <?php } ?>
            <?php }else { ?>
                <?php if (isset($_GET['sort'])) { ?>
                    <a href="<?=Url::to(['home/show-all', 'page' => 2, 'sort' => $_GET['sort']]) ?>">&raquo;</a>
                    <?php } else { ?>
                        <a href="<?=Url::to(['home/show-all', 'page' => 2]) ?>">&raquo;</a>
                        <?php } ?>
            <?php }?>
        <?php } ?>
</div>

</body>
</html>
 <script>
     var urlPara = new URLSearchParams(window.location.search);
     var paraValue = urlPara.get("page");
     var pageELement = document.querySelectorAll("a.page");
     if (paraValue) {
         for (let i = 0; i < pageELement.length; i++) {
             if (paraValue == parseInt(pageELement[i].textContent)) {
                 pageELement[i].style.backgroundColor = "red"; 
             } else {
                 pageELement[i].style.backgroundColor = "white";
             }
         }
     }
 </script>

frontend/views/home/test.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1> this is error</h1>
    <h2> hello responsive</h2>
</body>
</html>